### PR TITLE
fix: parse json5 codes always thorw JsonException 

### LINKED ISSUE #15: parse json5 codes always thorw JsonException on set JSON_THROW_ON_ERROR
Parse json5 codes always thorw JsonException on set JSON_THROW_ON_ERROR

## Detailed description

https://github.com/colinodell/json5/blob/7b4e50ca87ec5d51479dc563481e27ac14076221/src/Json5Decoder.php#L75-L80

in the code L76, if php version > 7.0 and set option JSON_THROW_ON_ERROR.

always thorw JsonException and interrupt subsequent processing

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Library version used (e.g. 1.0)
* PHP version used (e.g. PHP 5.6, PHP 7.0): PHP 7.0+
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):

-----

I think should auto remove JSON_THROW_ON_ERROR option on php > 7.0 in:

```
if (PHP_VERSION_ID >= 70000) { 
	// auto remove JSON_THROW_ON_ERROR option before call json_decode()
	
}
```

### PR DESCRIPTION
**Pull request by inhere**
## Description

fix: parse json5 codes always thorw JsonException on set JSON_THROW_ON_ERROR

## Motivation and context

Why is this change required? What problem does it solve?

- close #15 

## How has this been tested?

Please describe in detail how you tested your changes.

Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change adds a new code file, I have added the copyright header to it.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

File: src/Json5Decoder.php [hunk 1]
```diff
@@ -73,9 +73,10 @@ public static function decode($source, $associative = false, $depth = 512, $opti
         // Try parsing with json_decode first, since that's much faster
         // We only attempt this on PHP 7+ because 5.x doesn't parse some edge cases correctly
         if (PHP_VERSION_ID >= 70000) {
-            $result = \json_decode($source, $associative, $depth, $options);
-            if (\json_last_error() === \JSON_ERROR_NONE) {
-                return $result;
+            try {
+                $result = \json_decode($source, $associative, $depth, $options | \JSON_THROW_ON_ERROR);
```
Comment (andrew-demb) [inline src/Json5Decoder.php:77]:
```suggestion
                return \json_decode($source, $associative, $depth, $options | \JSON_THROW_ON_ERROR);
```

**Review by andrew-demb — CHANGES_REQUESTED** [review]

**Comment by colinodell** [comment]
I had to make a couple of small tweaks, mostly because I realized the approach I originally proposed wouldn't work on PHP 7.1 and 7.2 :facepalm:

Thanks for the contribution!

**Comment by glensc** [comment]
throw typo in title
